# services:
#   - type: web
#     name: image-classifier
#     env: python
#     buildCommand: pip install -r requirements.txt
#     startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 300 --workers 1 --max-requests 50 --worker-class sync
#     autoDeploy: true
#     healthCheckPath: /health
#     plan: free  # or starter/professional depending on your choice


services:
  - type: web
    name: image-classifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 300 --workers 1 --max-requests 50 --worker-class sync
    autoDeploy: true
    healthCheckPath: /health
    plan: free  # or starter/professional depending on your choice
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
